name: test-java
on:
  push:
    branches:
    - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - name: obtener y chequear repo
      uses: actions/checkout@v4

    - name: configurar java
      uses: actions/setup-java@v2
      #esto es para agregar parametros
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: test java
      run: |
        cd ejmploJava
        mvn test
